server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: on-trace-param

spring:
  datasource:
    url: jdbc:h2:mem:tests
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
